name: "PR Labels Check"
author: "Klaas Schoute <hello@student-techlife.com>"
description: "Github Action to manage labels on Pull Requests"

branding:
  icon: "check-circle"
  color: "green"

inputs:
  repo-token:
    description: "Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`."
    required: false
    default: ${{ github.token }}
  pr-number:
    description: "Pull Request number"
    required: false
    default: "${{ github.event.pull_request.number }}"
  valid-labels:
    description: "List of labels that are valid"
    required: true
  invalid-labels:
    description: "List of labels that are invalid"
    required: false
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"
