---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull request number to validate
        required: true
        type: number

jobs:
  validate:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
      - name: 🏷 Verify PR has a valid label
        uses: ./
        with:
          pr-number: >-
            ${{ github.event.pull_request.number || inputs.pr_number }}
          valid-labels: >-
            breaking-change, bugfix, documentation, enhancement, sync,
            refactor, performance, new-feature, maintenance, ci, dependencies
